---
services:
  tailscale-home-assistant:
    image: tailscale/tailscale:latest
    container_name: tailscale-home-assistant
    hostname: home-assistant
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - "TS_EXTRA_ARGS=--advertise-tags=tag:node --reset"
      - TS_SERVE_CONFIG=/config/home-assistant.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  home-assistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${PWD}/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true

volumes:
  home-assistant:
    driver: local
  tailscale-portainer-ce:
    driver: local
