---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        period: 24h
        prefix: index_

compactor:
  working_directory: /loki/compactor

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  enable_api: true

limits_config:
  allow_structured_metadata: false
