---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'n8n'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['n8n:443']
