---
name: Tests

on:
  workflow_call:

permissions:
  contents: 'read'
  pull-requests: 'read'
  checks: 'write'

jobs:
  source-protection:
    uses: ./.github/workflows/source-protection.yaml
    with:
      commitlint-config: '.github/.commitlintrc.yml'
      yamllint-config: '.github/.yamllintrc.yml'
